### ISSUE TITLE
Fetched GameJoltTrophy list is null

### ISSUE THREAD

**Issue by lespin** [raeleus/game-jolt-api#1]
In GameJoltTrophies.java

- `public TrophiesFetchValue handleResponse(JsonValue jsonValue)` parses all `GameJoltTrophy` from json, 
-  then places them in a ` Array<GameJoltTrophy> trophies`

But this array is never used after parsing : when the `TrophiesFetchValue` object is build,  parsed trophies are not set to its `trophies` attributes, resulting in a `null` Array in place of the parsed `GameJoltTrophy` list.

**Comment by raeleus** [comment]
I'll work on this as soon as I can.

**Comment by lespin** [comment]
Good. As far as I know, it's just a matter of adding one line. I can do a pull request if you want but it might not even be less work for you. Tell me!

**Comment by raeleus** [comment]
The fix should be in the latest version. Thank you so much!
